export interface Note {
  id: string; // Generated by backend
  title: string | null; // Backend allows null titles
  text: string; // Main content field from backend
  created_at: string; // ISO string format from backend
  updated_at: string; // ISO string format from backend
  url?: string | null; // Optional field
  isHtml?: boolean | null; // Optional field
  // Add score if needed for search results representation
  score?: number | null; 
}
