"""Rename content column to text in notes table

Revision ID: d359bbcc1abf
Revises: 7255d0b5c9aa
Create Date: 2025-04-13 01:19:55.388247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd359bbcc1abf'
down_revision: Union[str, None] = '7255d0b5c9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('text', sa.Text(), nullable=False))
    op.drop_column('notes', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('notes', 'text')
    # ### end Alembic commands ###
